### ISSUE TITLE
LVM lv remains on custom partitioning page

### ISSUE THREAD

**Issue by brs17** [pop-os/installer#82]
**Distribution - (run ```cat /etc/os-release```)**
 Pop!_OS 18.04 debug 8
 
**Issue/Bug Description**
On a machine that already has a drive partitioned with lvm, when using gparted to remove and repartition the drive, when the installer refreshes, the lvm partition is still there, blank.

![screenshot from 2018-04-11 19-57-24](https://user-images.githubusercontent.com/7460774/38644462-c3a9d8e0-3d9d-11e8-97d9-f346da562d48.png)

**Comment by mmstick** [comment]
I think this and other similar issues with LUKS/LVM are due to a timing issue with the deactivation & activation of LVM devices, and distinst requesting information too soon. I've noticed a similar issue with decrypting a LUKS device only for no LVM device to appear, or an empty LVM device (likely because the logical volumes on the logical device had not yet been activated yet).

**Comment by mmstick** [comment]
@brs17 Does this still happen for you?
